algorithm: 'COLDBREW'
task: 'node'
n_layer: 2
lr: 0.01
hidden_dim: 128
dropout: 0.2
weight_decay: 0.0005
epoch: 500
least_epoch: 40
patience: 100
exp_mode: 'coldbrew'
batch_size: 65536
epochs: 1500
samp_size_p: 200
samp_size_n_train: 200
samp_size_n_test_times_p: 20
dim_learnable_input: 0
unify_mlps: 0
force_set_to_best_config: 1
want_headtail: 1
num_layers: 2
studentMLP__skip_conn_T_and_res_blks: ''
StudentMLP__dim_model: -1
studentMLP__opt_lr: ''
LP__which_corr_and_DAD: ''
LP__num_propagations: -1
LP__alpha: -1
SEMLP_topK_2_replace: 2
SEMLP__include_part1out: 1
dropout_MLP: 0.2
SEMLP_part1_arch: '2layer'
has_proj2class: 0
whetherHasSE: '100'
se_reg: 32
graphMLP_reg: 0.0
graphMLP_tau: 2.0
graphMLP_r: 3
change_to_featureless: 0
do_deg_analyze: 1
train_which: 'TeacherGNN'
use_special_split: 1
optfun: 'torch.optim.Adam'
manual_assign_GPU: -9999
random_seed: 100
N_exp: 1
resume: False
cuda: True
cuda_num: 0
records_desc: 'res_connection'
records_path: '.'
compare_model: 0
type_model: 'GCN'
type_trick: 'Initial+BatchNorm'
layer_agg: 'concat'
res_alpha: 0.1
multi_label: False
dim_hidden: 64
transductive: True
float_or_double: 'float'
type_norm: 'None'
adj_dropout: 0.5
edge_dropout: 0.2
node_norm_type: 'n'
skip_weight: None
num_groups: None
prog: ''
rexName: 'res.npy'
graph_dropout: 0.2
layerwise_dropout: False