algorithm: 'GCN'
task: 'node'
n_layer: 2
lr: 0.01
hidden_dim: 128
dropout: 0.5
weight_decay: 0.0005
epoch: 500
least_epoch: 40
patience: 100
im_class_num: 3
im_ratio: 1
layer: 'gcn'
rw: 0.000001
ep_pre: 50
ep: 10000
ep_early: 1000
add_sl: True
adj_norm_1: True
adj_norm_2: False
nhid: 64
nhead: 1
wd: 5e-4
num_seed: 5
is_normalize: False
cls_og: 'GNN'
type: 'mid'
embedder: 'lte4g'
rec: False
lr_expert: 0.01
criterion: 'mean'
sep_class: 'pareto_73'
sep_degree: 5
class_weight: True
gamma: 1
alpha: 0.6
T: 1
expert_ep: 1000
curriculum_ep: 500
pretrained_encoder: False
save_encoder: False