algorithm: 'TAILGNN'
task: 'node'
lr: 0.01
hidden_dim: 128
dropout: 0.5
weight_decay: 0.0005
epoch: 1000
least_epoch: 40
patience: 200
hidden: 32
eta: 0.1
mu: 0.001
lamda: 0.0001
k: 5
arch: 1
id: 0
ablation: 0
g_sigma: 0.1