algorithm: 'TAM'
task: 'node'
backebone: 'GCN'
n_layer: 2
lr: 0.01
hidden_dim: 128
dropout: 0.5
weight_decay: 0.0005
epoch: 500
least_epoch: 40

warmup: 5
tam: True
tam_alpha: 2.5
tam_beta: 0.5
temp_phi: 1.2