# Data
dataset_name: 'computers'
data_dir: './data/computers/'
pretrained: null

# Output
out_dir: './out/computers/'

# Random seed
#seed: 42
#random_seed: 1234

# Model architecture
hidden_size: 256

# Regularization
dropout: 0.5
feat_adj_dropout: 0.5
gl_dropout: 0.5

# GNN
gnn: 'gcn'
graph_learn: True
graph_skip_conn: 0.8
update_adj_ratio: 0.1
graph_learn_regularization: False
smoothness_ratio: 0
degree_ratio: 0
sparsity_ratio: 0
graph_learn_ratio: 0
graph_learn_hidden_size: 40
graph_learn_epsilon: 0
graph_learn_topk: null
graph_learn_num_pers: 2
graph_hops: 2

# Training
optimizer: 'adam'
learning_rate: 0.01
weight_decay: 0.001
lr_patience: 2
lr_reduce_factor: 0.5
grad_clipping: null
grad_accumulated_steps: 1
early_stop_metric: 'acc'
pretrain_epoch: 0 # 0
max_iter: 2
eps_adj: 4e-5
shuffle: True
max_epochs: 150
patience: 1000
verbose: 20
print_every_epochs: 10
pe_every_epochs: 50
gpr_every_epochs: 50
num_anchors: 0

# Testing
out_raw_learned_adj_path: 'computers_adj.npy'
save_params: True
logging: True
out_predictions: True

# Device
no_cuda: False
cuda_id: 0