algorithm: 'SOLTGNN'
task: 'graph'
backbone: 'GIN'
n_layer: 2
lr: 0.01
dropout: 0.5
weight_decay: 0.0005
use_batch_norm: true
device: 0
batch_size: 32
epochs: 500
hidden_dim: 32
graph_pooling_type: "sum"
degree_as_tag: false
alpha: 0.5
mu1: 1.0
mu2: 1.0
lbd: 0.0001
dm: 64
K: 72
n_n: 1
n_g: 1
patience: 100
