algorithm: 'TopoImb'
task: 'graph'
backbone: 'GIN'
n_layer: 3
lr: 0.005
hidden_dim: 128
dropout: 0.5
weight_decay: 0.0005
epoch: 500
use_batch_norm: true
datatype: 'graph'
topo_initial: 'label'
shared_encoder: false
cls_layer: 2
res: false
reweighter: 'struct'
n_mem: [8,8,8,8,8]
use_key: false
att: 'dp'
reweight_weight: 0.2
reweight_task: ['wlcls']
pretrain_reweighter: false

# original config
imb_ratio: 0.9
nlayer: 3
nhid: 128
nclass: 2
nfeat: 64
epochs: 500
test_interval: 20
batch_size: 128
batch_nums: 6000
sup_ratio: 0.1
val_ratio: 0.3
test_raion: 0.6
model: 'gin'
explainer: 'gnnexplainer'
directional: false
edge_size: 0.05
edge_ent: 1.0
expl_loss: 'Tgt'
aligner: 'emb'
aligner_combine_weight: 1.0
align_emb: false
align_with_grad: false
split: 0
reweight_lr: 0.01
adv_step: 3
EM: false
intra_im_ratio: 0.1
inter_im_ratio: 0.6

