!!python/object:argparse.Namespace
dataset: CiteSeer
ens: false
factor_cb: 0.9999
factor_focal: 2.0
feat_dim: 16
imb_ratio: 1.0
keep_prob: 0.01
loss_name: re-weight
loss_type: ce
n_layer: 2
net: GCN
pc_softmax: false
pred_temp: 2
renode: false
reweight: false
rn_base: 0.5
rn_max: 1.5
shuffle_seed: 34
tam: true
tam_alpha: 2.5
tam_beta: 0.5
temp_phi: 1.2
warmup: 5
