!!python/object:argparse.Namespace
backbone: gcn
batch_size: 128
beta: 0.3
dataset: COLLAB
epochs: 500
feature_dim: 10
graph_pooling_type: average
hidden_dim: 96
hidden_graphs: 6
imb: 1.0
lr: 0.01
max_step: 4
n_split: 2
nclass: 2
normalize: true
num_layers: 1
penultimate_dim: 32
seed: 10
size_hidden_graphs: 4
