!!python/object:argparse.Namespace
backbone: Gcn
dataset: computers
epoch: 500
gpu: 1
hid_dim: 256
loss_hp: 1
lr: 0.01
num_layers: 2
run_times: 10
shuffle_seed: 1
split: 0
stop_step: 50
weight_decay: 0.0005
