EM: false
adv_step: 1
align_emb: false
align_weight: 1.0
align_with_grad: false
aligner: emb
aligner_combine_weight: 1.0
att: dp
baseline: 'no'
batch_nums: 6000
batch_size: 128
c_train_num:
- 216
- 217
c_val_num:
- 216
- 216
cuda: true
dataset: FRANKENSTEIN
datatype: graph
directional: false
dropout: 0.5
edge_ent: 1.0
edge_size: 0.05
epochs: 500
expl_loss: Tgt
explainer: gnnexplainer
imb_ratio: 0.5
inter_im_ratio: 0.6
intra_im_ratio: 0.5
load: null
load_config: false
load_model: null
log: false
lr: 0.001
model: gcn
n_class: 2
n_mem:
- 8
- 8
- 8
- 8
- 8
nclass: 2
nfeat: 6
nhid: 128
nlayer: 5
no_cuda: false
num_train: 433
num_val: 216
pretrain_reweighter: false
res: false
reweight_lr: 0.01
reweight_task:
- wlcls
reweight_weight: 0.2
reweighter: struct
save: false
seed: 10
shared_encoder: false
sparse: false
split: 0
sup_ratio: 0.1
task: gcls
test_ratio: 0.6
topo_initial: label
use_key: false
val_ratio: 0.3
weight_decay: 0.0005
