aug: RE
aug_num: 2
batch_size: 128
bb: gcn
dataset: REDDIT-BINARY
drop_edge_ratio: 0.1
dropout: 0.5
early_stopping: 50
epochs: 500
imb_ratio: 0.9
kernel_type: SP
knn_layer: 3
knn_nei_num: 3
lr: 0.005
mask_node_ratio: 0.0
n_hidden: 32
num_train: 59
num_val: 59
prop_epochs: 3
runs: 10
seed: 10
setting: knn_aug
smote_k: 10
temp: 0.5
weight_decay: 0.0
