!!python/object:argparse.Namespace
balance_train_each: 20
beta: 0.5
dataset: actor
dropout: 0.7
early_stop: 20
epoch: 500
factor_cb: 0.9999
factor_focal: 2.0
gamma: 1.0
gem_file: ./datasets//actor_0.15_gem.pt
gpu: 0
imb_ratio: 5.0
is_imb: false
labeling_ratio: 0.1
least_epoch: 40
loss: ExpGAUC
lr: 0.01
lr_decay_epoch: 10
lr_decay_rate: 0.95
model: gcn
nni: 0
num_class: 7
num_feature: 745
num_hidden: 64
num_layer: 2
pagerank_prob: 0.15
pair_ner_diff: 1
ppr_topk: -1
renode_reweight: 0
rn_base_weight: 0.5
rn_scale_weight: 1.0
run_init_num: 10
run_split_num: 1
save_repeated_res: 1
saved_model: saved_models/actor_gcn_ExpGAUC_is_renode_0_best_model.pt
seed_list:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
shuffle_seed: 40
shuffle_seed_list:
- 0
topo_dim: 64
valid_each: 30
warm_up_epoch: 0
warm_up_loss: focal
weight_decay: 0
weight_global_dim: 64
weight_inter_dim: 64
weight_sub_dim: 64
