algorithm: 'G2GNN'
task: 'graph'
backbone: 'GCN'
setting: 'knn_aug'
aug_num: 2
kernel_type: SP
knn_layer: 3
knn_nei_num: 3
n_layer: 2
lr: 0.005
hidden_dim: 128
dropout: 0.5
weight_decay: 0.01
epoch: 500
use_batch_norm: true
mask_node_ratio: 0.0
drop_edge_ratio: 0.005
temp: 0.5